# vim:ft=yaml.ansible:
---
- name: X11 | Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - compton
    - mesa
    - scrot
    - vulkan-intel
    - xdotool
    - xorg-server
    - xorg-xdpyinfo
    - xorg-xinput
  become: true

- name: X11 | Configure xorg to run with root privileges
  copy:
    dest: /etc/X11/Xwrapper.config
    src: Xwrapper.config
  become: true

- name: X11 | Make xorg config dir
  become: true
  file:
    path: /etc/X11/xorg.conf.d
    state: directory

- name: X11 | Install xorg monitor config
  template:
    dest: /etc/X11/xorg.conf.d/90-monitor.conf
    src: templates/xorg-monitor.conf.j2
  become: true

- name: X11 | Generate base16 configs
  base16_builder:
    scheme: "{{ base16_scheme }}"
    scheme_family: "{{ base16_scheme_family }}"
    template: xresources
    schemes_source: "{{ base16_schemes_source }}"
  register: base16_xresources
  tags: [base16]

- name: X11 | Configure Xresources
  template:
    src: templates/Xresources.j2
    dest: "/home/{{ user.name }}/.Xresources"
    owner: "{{ user.name }}"
  tags: [base16]

- name: X11 | Install compton service
  copy:
    dest: "/home/{{ user.name }}/.config/systemd/user/compton.service"
    src: compton.service

- name: X11 | Enable compton service
  become: true
  become_user: "{{ user.name }}"
  when: window_manager == "i3"
  systemd:
    enabled: true
    name: compton.service
    user: true
    daemon-reload: true
